### PR TITLE
p5js rest of image, environment and transform sections

### PR DESCRIPTION
**Pull request by anthonygalea**
Covered almost all remaining functions in these sections, but not sure how best to adapt snippets for `mask-image` and `blend`. They are currently working with graphics not image. Any ideas?

### CODE REVIEW

**Comment by nbeloglazov** [comment]
And we can't switch snippets to use image because there is no API to create new images, only `create-graphics`?

**Comment by nbeloglazov** [comment]
Oh, wait, there is [`create-image`](http://quil.info/api/image#create-image). Is it possible to switch snippets to use it?

**Comment by anthonygalea** [comment]
Yes. [This](https://github.com/anthonygalea/quil/commit/8d4c8f4f0c06e6b5d244c3f04a5935c22e8f3a0c) would be `mask-image`. Works in `cljs` but in `clj` I don't see the masked image for some reason. And for `blend` we could do [this](https://github.com/anthonygalea/quil/commit/7f2cf28efac7b7e2a6cd9ffbc9fb7a9aad975fbe) but in `cljs` `(q/background)` doesn't work when `blend` is used in the snippet. Not sure why.

**Comment by nbeloglazov** [comment]
Refactored `mask-image` in https://github.com/quil/quil/commit/a5b61880bf7d0a9247fdbd31ecfedce1caed352a. The problem was that in clj version mask image uses blue channel, not alpha channel for "grayscaleness". I changed our clj implementation to instead extract alpha values from mask image into an array and pass array instead of Image.

**Comment by nbeloglazov** [comment]
Not sure what is up with `blend`. p5js examples use image as background, maybe that somehow supported while color background is not supported? Don't quite understand it.

**Pull request merged**
