### PR TITLE
Make current-fill and current-stroke work for cljs

### PR DESCRIPTION
**Pull request by satchit8**
As per #194.

### CODE REVIEW

**Comment by nbeloglazov** [comment]
Please also enable tests for current-fill and current-stroke for clojurescript in the same pull request: https://github.com/quil/quil/blob/738a549cb3704e3d09fe0de9c88c486d35a1d6d0/test/cljc/snippets/color/creating_and_reading.cljc#L128

**Comment by nbeloglazov** [comment]
Thanks!

**Comment by satchit8** [comment]
Does the additional commit look appropriate?

As for confirming that the tests were enabled, I tried:

    lein with-profile cljs-testing ring server

then observed some results in a browser window, but didn't catch whether the tests in question ran and what the results were.

**Comment by nbeloglazov** [comment]
Yes, looks good. The tests are pretty primitive: all they do is check that no js error thrown. Basically that all calls work without errors. They don't check any visual rendering. So ideally, if we enabled tests before you commit we'd see 2 js erros in console saying that current-fill doesn't work.

**Comment by satchit8** [comment]
Thanks for the explanation.  Had success in verifying your instructions :)

**Pull request merged**
