### PR TITLE
p5 shape

### PR DESCRIPTION
**Pull request by anthonygalea**
From what I understood it makes sense to use p5's `loadModel` and `model` functions from quil's `load-shape` and `shape` but when I tried adapting the snippets I don't see any output even with the simple example which works on the p5 [documentation](https://p5js.org/reference/#/p5/loadModel). Any ideas?

### CODE REVIEW

**Comment by nbeloglazov** [comment]
Loading shape is asynchronous in p5js so we can't use it immediately. I moved `load-shape` to `setup` and it worked ok (even without checking whether it's loaded or not in `draw`): 

```clj
(ns sample
  (:require [quil.core :as q :include-macros true]
            [quil.middleware :as m]))

(defn setup []
  (q/frame-rate 30)
  (q/color-mode :hsb)
  {:shape (q/load-shape "/test/html/octahedron.obj")
   :angle 0})

(defn draw-state [state]
  (q/orbit-control)
  (q/background 240)
  (q/shape (:shape state)))

(q/defsketch my
  :host "host"
  :size [500 500]
  :renderer :p3d
  :setup setup
  :draw draw-state
  :middleware [m/fun-mode])
```

Given that we a getting more asynchronous loading functions I'm wondering if it would be better to add `loaded?` function that takes object like shape, image, shader, whatever and tells you whether it finished loading. That way user doesn't need to how to check whether specific type of object finished loading. Also it gives us freedom to devise special custom ways of checking for loading. 

For example I checked p5js code for p5.Geometry class which is returned from `loadModel` and couldn't see easy way to check whether it's finished loading or not. One way we could implement it ourselves is to pass callback to `loadModel` call and when callback is called set some custom 'quilModelLoaded' attribute on the Geometry instance and later check for this attribute from the `loaded?` function.

I saw your suggestion about supporting `preload` but I'm somehwat hesitant about adding it as we would need to support it for java version as well and also somehow integrate with state object as preload supposed to load things so it'd make sense for this function to return these objects.  

What do you think?

**Comment by anthonygalea** [comment]
Yes I think adding a `loaded?` functions makes sense. Will add it with the `shader` pull request. Should we also remove one of the snippets? They are almost exactly the same.

**Comment by nbeloglazov** [comment]
Which snippets are you talking about?

**Comment by anthonygalea** [comment]
`load-shape` and `shape`

**Comment by nbeloglazov** [comment]
Yes, removing one of them makes sense.

**Pull request merged**
